# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: quildtide@gmail.com
CodeOfConductContact: quildtide@gmail.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: quildtide@gmail.com
MarkdownIndentation: 2
PackageName: Hranrad
PackageOwner: quildtide
PackageUUID: b55c4a7e-e4ca-58bb-a587-fc830436a95b
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
